name: Continuous testing

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    strategy:
      matrix:
        command: [lint, build, test]
    runs-on: ubuntu-latest
    name: running ${{ matrix.command }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          package-manager-cache: false

      - name: Determine pnpm store path
        id: pnpm-store
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - run: pnpm install

      - run: yarn run ${{ matrix.command }}

  conclude:
    runs-on: ubuntu-latest
    name: All tests passed
    needs: [test]

    steps:
      - run: echo '### Good job! All the tests passed ðŸš€' >> $GITHUB_STEP_SUMMARY
